# Generated by Django 5.1.5 on 2025-01-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Question',
            new_name='question',
        ),
    ]
