# Generated by Django 5.1.5 on 2025-01-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0004_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
    ]
