# Generated by Django 5.1.5 on 2025-01-22 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0005_remove_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizmania.difficulty'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/covers/%Y/%m/%d/'),
        ),
    ]
