# Generated by Django 5.1.5 on 2025-01-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0007_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='qnt_diff_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='qnt_easy_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='qnt_mid_questions',
            field=models.IntegerField(default=0),
        ),
    ]
