# Generated by Django 5.1.5 on 2025-01-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0008_quiz_qnt_diff_questions_quiz_qnt_easy_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='qnt_diff_questions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='qnt_easy_questions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='qnt_mid_questions',
            field=models.IntegerField(null=True),
        ),
    ]
