# Generated by Django 5.1.5 on 2025-01-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0009_alter_quiz_qnt_diff_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='qnt_diff_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='qnt_easy_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='qnt_mid_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
