# Generated by Django 5.1.5 on 2025-01-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0010_remove_question_quiz_alter_quiz_qnt_diff_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizmania.difficulty'),
        ),
    ]
