# Generated by Django 5.1.5 on 2025-01-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0011_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='competed_quizes',
            new_name='completed_quizes',
        ),
        migrations.AddField(
            model_name='profile',
            name='incorrect_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='correct_questions',
        ),
        migrations.AddField(
            model_name='profile',
            name='correct_questions',
            field=models.IntegerField(default=0),
        ),
    ]
