# Generated by Django 5.1.5 on 2025-01-28 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0012_rename_competed_quizes_profile_completed_quizes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_list', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifes', models.IntegerField(blank=True, default=0)),
                ('correct_answers', models.IntegerField(blank=True, default=0)),
                ('incorrect_answers', models.IntegerField(blank=True, default=0)),
                ('correct_answers_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizmania.question')),
                ('current_quiz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quizmania.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
