# Generated by Django 5.1.5 on 2025-01-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0013_quizsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correct_questions_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
