# Generated by Django 5.1.5 on 2025-01-28 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0014_profile_correct_questions_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='current_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizmania.quiz'),
        ),
    ]
