# Generated by Django 5.1.5 on 2025-01-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0015_alter_quizsession_current_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='incorrect_questions_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
