# Generated by Django 5.1.5 on 2025-01-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0016_profile_incorrect_questions_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='correct_questions_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='incorrect_questions_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
