# Generated by Django 5.1.5 on 2025-01-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0017_alter_profile_correct_questions_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
