# Generated by Django 5.1.5 on 2025-01-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0018_quizsession_current_question_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='current_question_index',
        ),
        migrations.AddField(
            model_name='quizsession',
            name='last_question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
