# Generated by Django 5.1.5 on 2025-01-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizmania', '0019_remove_quizsession_current_question_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='last_question_id',
        ),
    ]
